<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClinicHistorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('clinical_histories')->insert([
            [
                'number' => 1001,
                'reason' => 'Consulta rutinaria',
                'mucous' => 'Normales',
                'anamnesis' => 'Sin antecedentes',
                'diagnosis' => 'Salud general buena',
                'treatment' => 'Ninguno',
                'price' => 30.00,
                'date' => '2024-07-01',
                'pet_id' => 1,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1002,
                'reason' => 'Problemas digestivos',
                'mucous' => 'Pálidas',
                'anamnesis' => 'Dieta reciente cambio',
                'diagnosis' => 'Gastritis leve',
                'treatment' => 'Medicamento antiácido',
                'price' => 45.00,
                'date' => '2024-07-02',
                'pet_id' => 2,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1003,
                'reason' => 'Vacunación anual',
                'mucous' => 'Normales',
                'anamnesis' => 'Vacunas al día',
                'diagnosis' => 'Vacunación completa',
                'treatment' => 'Vacuna aplicada',
                'price' => 50.00,
                'date' => '2024-07-04',
                'pet_id' => 3,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1004,
                'reason' => 'Chequeo dental',
                'mucous' => 'Levemente inflamadas',
                'anamnesis' => 'Problemas dentales previos',
                'diagnosis' => 'Cálculo dental',
                'treatment' => 'Limpieza dental',
                'price' => 75.00,
                'date' => '2024-07-09',
                'pet_id' => 4,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1005,
                'reason' => 'Herida en la pata',
                'mucous' => 'Normales',
                'anamnesis' => 'Accidente reciente',
                'diagnosis' => 'Herida en la pata izquierda',
                'treatment' => 'Antibióticos y vendaje',
                'price' => 60.00,
                'date' => '2024-07-12',
                'pet_id' => 5,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1006,
                'reason' => 'Problemas respiratorios',
                'mucous' => 'Cianóticas',
                'anamnesis' => 'Exposición a humo',
                'diagnosis' => 'Bronquitis',
                'treatment' => 'Inhalador y descanso',
                'price' => 80.00,
                'date' => '2024-07-10',
                'pet_id' => 6,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1007,
                'reason' => 'Control de peso',
                'mucous' => 'Normales',
                'anamnesis' => 'Sobrepeso',
                'diagnosis' => 'Obesidad leve',
                'treatment' => 'Dieta controlada y ejercicio',
                'price' => 40.00,
                'date' => '2024-07-13',
                'pet_id' => 7,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1008,
                'reason' => 'Infección urinaria',
                'mucous' => 'Normales',
                'anamnesis' => 'Frecuencia urinaria alta',
                'diagnosis' => 'Cistitis',
                'treatment' => 'Antibióticos',
                'price' => 55.00,
                'date' => '2024-07-16',
                'pet_id' => 8,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1009,
                'reason' => 'Chequeo general',
                'mucous' => 'Normales',
                'anamnesis' => 'Ninguna',
                'diagnosis' => 'Salud general óptima',
                'treatment' => 'Ninguno',
                'price' => 25.00,
                'date' => '2024-07-20',
                'pet_id' => 9,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1010,
                'reason' => 'Diarrea persistente',
                'mucous' => 'Deshidratadas',
                'anamnesis' => 'Cambio en la dieta',
                'diagnosis' => 'Gastroenteritis',
                'treatment' => 'Suero y dieta blanda',
                'price' => 70.00,
                'date' => '2024-07-22',
                'pet_id' => 10,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1011,
                'reason' => 'Examen de sangre',
                'mucous' => 'Normales',
                'anamnesis' => 'Chequeo rutinario',
                'diagnosis' => 'Todos los parámetros normales',
                'treatment' => 'Ninguno',
                'price' => 90.00,
                'date' => '2024-07-23',
                'pet_id' => 7,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1012,
                'reason' => 'Problema ocular',
                'mucous' => 'Normales',
                'anamnesis' => 'Enrojecimiento ocular',
                'diagnosis' => 'Conjuntivitis',
                'treatment' => 'Gotas oculares',
                'price' => 65.00,
                'date' => '2024-07-24',
                'pet_id' => 1,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1013,
                'reason' => 'Dolor abdominal',
                'mucous' => 'Pálidas',
                'anamnesis' => 'Dolor reciente',
                'diagnosis' => 'Distensión abdominal',
                'treatment' => 'Medicamentos y dieta controlada',
                'price' => 85.00,
                'date' => '2024-07-25',
                'pet_id' => 4,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1014,
                'reason' => 'Corte en la pata',
                'mucous' => 'Normales',
                'anamnesis' => 'Accidente doméstico',
                'diagnosis' => 'Corte superficial',
                'treatment' => 'Limpieza y puntos',
                'price' => 50.00,
                'date' => '2024-07-28',
                'pet_id' => 3,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'number' => 1015,
                'reason' => 'Fiebre alta',
                'mucous' => 'Rojizas',
                'anamnesis' => 'Síntomas de fiebre',
                'diagnosis' => 'Fiebre sin causa aparente',
                'treatment' => 'Medicamentos antipiréticos',
                'price' => 95.00,
                'date' => '2024-07-29',
                'pet_id' => 2,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
