<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VisitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'heart_rate' => 80,
                'respiratory_rate' => 20,
                'temperature' => 37.5,
                'anamnesis' => 'Sin antecedentes',
                'symptoms' => 'Consulta rutinaria',
                'exams' => null,
                'differential_diagnosis' => null,
                'definitive_diagnosis' => 'Salud general buena',
                'treatment' => 'Ninguno',
                'exam_results' => null,
                'recommendations' => null,
                'recipes' => null,
                'weight' => 10.5,
                'price' => 30.00,
                'date' => '2024-07-01',
                'time' => '10:00:00',
                'clinical_history_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'heart_rate' => 90,
                'respiratory_rate' => 25,
                'temperature' => 38.0,
                'anamnesis' => 'Dieta reciente cambio',
                'symptoms' => 'Problemas digestivos',
                'exams' => null,
                'differential_diagnosis' => null,
                'definitive_diagnosis' => 'Gastritis leve',
                'treatment' => 'Medicamento antiácido',
                'exam_results' => null,
                'recommendations' => null,
                'recipes' => null,
                'weight' => 12.3,
                'price' => 45.00,
                'date' => '2024-07-02',
                'time' => '10:30:00',
                'clinical_history_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'heart_rate' => 85,
                'respiratory_rate' => 22,
                'temperature' => 37.8,
                'anamnesis' => 'Vacunas al día',
                'symptoms' => 'Vacunación anual',
                'exams' => null,
                'differential_diagnosis' => null,
                'definitive_diagnosis' => 'Vacunación completa',
                'treatment' => 'Vacuna aplicada',
                'exam_results' => null,
                'recommendations' => null,
                'recipes' => null,
                'weight' => 11.0,
                'price' => 50.00,
                'date' => '2024-07-04',
                'time' => '11:00:00',
                'clinical_history_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'heart_rate' => 78,
                'respiratory_rate' => 18,
                'temperature' => 37.5,
                'anamnesis' => 'Problemas dentales previos',
                'symptoms' => 'Chequeo dental',
                'exams' => null,
                'differential_diagnosis' => null,
                'definitive_diagnosis' => 'Cálculo dental',
                'treatment' => 'Limpieza dental',
                'exam_results' => null,
                'recommendations' => null,
                'recipes' => null,
                'weight' => 9.8,
                'price' => 75.00,
                'date' => '2024-07-09',
                'time' => '09:30:00',
                'clinical_history_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'heart_rate' => 85,
                'respiratory_rate' => 21,
                'temperature' => 37.9,
                'anamnesis' => 'Accidente reciente',
                'symptoms' => 'Herida en la pata',
                'exams' => null,
                'differential_diagnosis' => null,
                'definitive_diagnosis' => 'Herida en la pata izquierda',
                'treatment' => 'Antibióticos y vendaje',
                'exam_results' => null,
                'recommendations' => null,
                'recipes' => null,
                'weight' => 10.0,
                'price' => 60.00,
                'date' => '2024-07-12',
                'time' => '10:45:00',
                'clinical_history_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'heart_rate' => 92,
                'respiratory_rate' => 30,
                'temperature' => 38.5,
                'anamnesis' => 'Exposición a humo',
                'symptoms' => 'Problemas respiratorios',
                'exams' => null,
                'differential_diagnosis' => null,
                'definitive_diagnosis' => 'Bronquitis',
                'treatment' => 'Inhalador y descanso',
                'exam_results' => null,
                'recommendations' => null,
                'recipes' => null,
                'weight' => 11.5,
                'price' => 80.00,
                'date' => '2024-07-10',
                'time' => '11:15:00',
                'clinical_history_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'heart_rate' => 88,
                'respiratory_rate' => 24,
                'temperature' => 37.6,
                'anamnesis' => 'Sobrepeso',
                'symptoms' => 'Control de peso',
                'exams' => null,
                'differential_diagnosis' => null,
                'definitive_diagnosis' => 'Obesidad leve',
                'treatment' => 'Dieta controlada y ejercicio',
                'exam_results' => null,
                'recommendations' => null,
                'recipes' => null,
                'weight' => 13.0,
                'price' => 40.00,
                'date' => '2024-07-13',
                'time' => '10:00:00',
                'clinical_history_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'heart_rate' => 85,
                'respiratory_rate' => 25,
                'temperature' => 38.0,
                'anamnesis' => 'Frecuencia urinaria alta',
                'symptoms' => 'Infección urinaria',
                'exams' => null,
                'differential_diagnosis' => null,
                'definitive_diagnosis' => 'Cistitis',
                'treatment' => 'Antibióticos',
                'exam_results' => null,
                'recommendations' => null,
                'recipes' => null,
                'weight' => 12.0,
                'price' => 55.00,
                'date' => '2024-07-16',
                'time' => '11:30:00',
                'clinical_history_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'heart_rate' => 78,
                'respiratory_rate' => 20,
                'temperature' => 37.3,
                'anamnesis' => 'Ninguna',
                'symptoms' => 'Chequeo general',
                'exams' => null,
                'differential_diagnosis' => null,
                'definitive_diagnosis' => 'Salud general óptima',
                'treatment' => 'Ninguno',
                'exam_results' => null,
                'recommendations' => null,
                'recipes' => null,
                'weight' => 11.8,
                'price' => 25.00,
                'date' => '2024-07-20',
                'time' => '10:15:00',
                'clinical_history_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'heart_rate' => 82,
                'respiratory_rate' => 22,
                'temperature' => 37.9,
                'anamnesis' => 'Cambio en la dieta',
                'symptoms' => 'Diarrea persistente',
                'exams' => null,
                'differential_diagnosis' => null,
                'definitive_diagnosis' => 'Gastroenteritis',
                'treatment' => 'Suero y dieta blanda',
                'exam_results' => null,
                'recommendations' => null,
                'recipes' => null,
                'weight' => 10.2,
                'price' => 70.00,
                'date' => '2024-07-22',
                'time' => '10:30:00',
                'clinical_history_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        
        DB::table('visits')->insert($data);
        
    }
}
